baseURL = 'https://thomassteendijk.github.io/thomassteendijk/'
languageCode = 'en-us'
title = 'Thomas Steendijk Home'
subtitle = "test"
theme = "hugo-theme-learn" 

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "blue"
  featured_image = ""
  recent_posts_number = 1